elasticsearch:
  host: 47.94.140.241
  port: 9200
  user: elastic
  pwd: test123
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500
spring:
  cloud:
    sentinel:
      transport:
        port: 8099
        dashboard: 127.0.0.1:8080
